Repository difizen/libro, pull requests merged in 2024-11, with the labels that each got.

#322 chore: add discord release action
  .github/workflows/discord-release.yml
Labels: PR: reviewed-approved

#324 fix: pr label by title action
  .github/workflows/pr-label-title-body.yml
Labels: PR: reviewed-approved, PR: chore

#323 docs: update discord link
  README.md
  README_zh.md
Labels: PR: unreviewed, PR: documentation

#328 fix: pr label action
  .github/workflows/pr-label-title-body.yml
Labels: PR: reviewed-approved, PR: chore

#330 docs: add code of conduct
  CODE_OF_CONDUCT.md
Labels: PR: reviewed-approved, PR: documentation

#332 docs: update readme
  README.md
  README_zh.md
Labels: PR: reviewed-approved, PR: documentation, PR: chore

#334 docs: add security policy
  SECURITY.md
Labels: PR: reviewed-approved, PR: documentation

#333 docs: update libro guide book
  examples/libro_guide_book.ipynb
  examples/sql_demo
Labels: PR: reviewed-approved, PR: documentation, PR: chore

#336 docs: update contact info on readme
  README.md
  README_zh.md
Labels: PR: reviewed-approved, PR: documentation, size/S

#337 chore: manage labels
  .github/labels.yml
  .github/workflows/pr-label-title-body.yml
Labels: PR: reviewed-approved, PR: documentation, PR: chore, size/L

#339 chore: add codeowners
  .github/workflows/pr-label-title-body.yml
  CODEOWNERS
  packages/libro-ai-native/CODEOWNERS
  packages/libro-app/CODEOWNERS
  packages/libro-code-cell/CODEOWNERS
  packages/libro-code-editor/CODEOWNERS
  packages/libro-codemirror/CODEOWNERS
  packages/libro-cofine-editor-contribution/CODEOWNERS
  packages/libro-cofine-editor-core/CODEOWNERS
  packages/libro-cofine-editor/CODEOWNERS
  packages/libro-cofine-textmate/CODEOWNERS
  packages/libro-kernel/CODEOWNERS
  packages/libro-l10n/CODEOWNERS
  packages/libro-language-client/CODEOWNERS
  packages/libro-lsp/CODEOWNERS
  packages/libro-markdown-cell/CODEOWNERS
  packages/libro-markdown/CODEOWNERS
  packages/libro-rendermime/CODEOWNERS
  packages/libro-search-code-cell/CODEOWNERS
  packages/libro-search/CODEOWNERS
  packages/libro-shared-model/CODEOWNERS
  packages/libro-sql-cell/CODEOWNERS
  packages/libro-terminal/CODEOWNERS
  packages/libro-toc/CODEOWNERS
  packages/libro-virtualized/CODEOWNERS
  packages/libro-widget/CODEOWNERS
Labels: PR: reviewed-approved, size/M, pkg:libro-ai-native, pkg:libro-app, pkg:libro-code-cell, pkg:libro-code-editor, pkg:libro-codemirror, pkg:libro-cofine-editor, pkg:libro-cofine-editor-contribution, pkg:libro-cofine-editor-core, pkg:libro-cofine-textmate, pkg:libro-kernel, pkg:libro-l10n, pkg:libro-language-client, pkg:libro-lsp, pkg:libro-markdown, pkg:libro-markdown-cell, pkg:libro-rendermime, pkg:libro-search, pkg:libro-search-code-cell, pkg:libro-shared-model, pkg:libro-sql-cell, pkg:libro-terminal, pkg:libro-toc, pkg:libro-virtualized, pkg:libro-widget

#343 chore(lab): update guidebook content
  examples/libro_guide_book.ipynb
  examples/libro_guide_book_zh.ipynb
  examples/sql_demo
  examples/sql_demo.db
  packages/libro-lab/src/guide/libro_guide_book.json
  packages/libro-lab/src/guide/libro_guide_book_zh.json
Labels: PR: reviewed-approved, PR: chore, size/L, pkg:libro-lab

#340 fix: improve markdown style
  packages/libro-app/src/index.less
  packages/libro-core/src/index.less
Labels: PR: unreviewed, PR: fix, size/XS, pkg:libro-app, pkg:libro-core
